### ISSUE TITLE
Project Update: Godot has glTF export

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Project-Explorer#107]
Godot is already in Project Explorer because of its glTF import.  Can we also add that it does export?

via https://github.com/KhronosGroup/glTF/issues/1986

**Comment by aaronfranke** [comment]
Also, I see the description is "Godot 3.0 fully supports glTF import". This is incorrect. Godot did not glTF import until version 3.2, and Godot will not have glTF export until version 3.4 (it's merged in master, but not in a stable release yet).

**Comment by javagl** [comment]
@aaronfranke Is there a rough timeline for this update? Depending on that, the update of the description could be done in one PR (maybe based on your suggestions/input, if you have any)

**Comment by aaronfranke** [comment]
@javagl Version 3.4 will likely come out either this year or early next year. Godot does not have fixed release timelines, so it's hard to be more certain than that.

**Comment by javagl** [comment]
Then we can leave this issue open for now. (The description may be updated from "Godot 3.0 fully supports glTF import" to "Godot 3.2 fully supports glTF import", before that, but that's probably not urgent)

**Comment by aaronfranke** [comment]
Godot 3.4 has now been released, we can update this documentation now (3.2+ has GLTF import, 3.4+ has GLTF export).

**Comment by javagl** [comment]
@aaronfranke If https://github.com/KhronosGroup/glTF-Project-Explorer/pull/131/files is OK, that could be merged and this issue be closed.
