### ISSUE TITLE
Upcoming renaming of master -> main branch planned for late August 2021

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/glTF-Project-Explorer#116]
@weegeekps @emackey @javagl @lexaknyazev  and other interested parties: heads-up that we propose to rename the default branch of this repository to 'main' in late August 2021, following emerging Khronos & github practice (for Khronos members, see internal khronos-general issue 106). This will have very little impact, although if you have a checked-out repository clone, you may want to follow the simple instructions github will pop up on the repository webpage describing how to do the same locally.

If there is a concern about this, please raise it here by 2021-08-23.

**Comment by oddhack** [comment]
@outofcontrol branch renaming has been done, but I think you might need to update the local view under https://github.khronos.org/glTF-Project-Explorer/ to track 'main' branch as well - that's outside the registry system so leaving in your hands.

**Comment by outofcontrol** [comment]
The local view is pulled from branch `gh-pages` so no changes needed. This is setup in GitHub under settings -> Pages.
