### ISSUE TITLE
New project: GLTF-tool

### ISSUE THREAD

**Issue by fferri** [KhronosGroup/glTF-Project-Explorer#147]
> A tool to view most of the data contained in a glTF file, with hyperlinks to follow the references across different sections within the file.

[fferri/GLTF-tool](https://github.com/fferri/GLTF-tool)

**Comment by javagl** [comment]
The link does not work for me - could it be that you have marked this as a 'private' repository or so...?

**Comment by fferri** [comment]
Right. It should be now fixed. Sorry about that.

**Comment by javagl** [comment]
A PR is at https://github.com/KhronosGroup/glTF-Project-Explorer/pull/148 . I could self-merge it immediately, but maybe you want to have a look at [the entry](https://github.com/KhronosGroup/glTF-Project-Explorer/pull/148/files) and give a 👍 if this is OK.

**Comment by fferri** [comment]
Done. Thanks
