### ISSUE TITLE
Add Khronos glTF Compressor

### ISSUE THREAD

**Issue by abasilak** [KhronosGroup/glTF-Project-Explorer#177]
Khronos has recently released the open source glTF-Compressor tool for interactively optimizing and fine tuning texture compression settings, to help users adjust their 3D assets for optimal web delivery. More details here:
https://www.khronos.org/blog/optimize-3d-assets-with-khronos-new-gltf-compressor-tool

The JSON properties for this project are:
{
  "name" : "Khronos glTF Compressor",
  "description" : "Khronos sample viewer with compression capabilities ([source code](https://github.com/KhronosGroup/glTF-Compressor))",
  "link" : "https://github.com/KhronosGroup/glTF-Compressor",
  "task" : [ "load", "view", "optimize","export" ],
  "type" : [ "web application" ],
  "inputs" : [ "glTF 2.0" ],
  "outputs": ["glTF 2.0"],
  "tags": ["Khronos Official"]
}

**Comment by javagl** [comment]
This was added manually via the submission form in the meantime, and should appear on the live page soon.
