### ISSUE TITLE
The title search filter should be case INsensitive

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Project-Explorer#20]
According to feedback via mail, searching for a title should be case-**in**sensitive. (There are many variations of glTF, GLTF, gltf... so this certainly makes sense).

From my understanding, it should be sufficient to change the line https://github.com/KhronosGroup/glTF-Project-Explorer/blob/master/src/store/results/Sagas.ts#L67

    return projects.filter(p => p.name.includes(titleSubstring));

to 

    return projects.filter(p => p.name.toLowerCase().includes(titleSubstring.toLowerCase()));

Any issues with that? 
(An alternative would be some RegEx magic, but that shouldn't be necessary here...)

**Comment by weegeekps** [comment]
Yeah, I agree with this. This is a good change, feel free to submit the PR for it. I am currently figuring out the GitHub Actions for deployment.
