### ISSUE TITLE
&lt;model-viewer> tag not rendering properly in title

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/glTF-Project-Explorer#29]
On the [Project Explorer Page](http://github.khronos.org/glTF-Project-Explorer/) page the &lt;model-viewer&gt; is rendering as &amp;lt;model-viewer> in the title. It appears to render correctly further down on the page when mentioned in the description for three.js glTF loader.

**Comment by javagl** [comment]
@Khronoswebmaster 

The data file does not seem to be reflected in the deployed state. I think this happened automagically during the first deployment, and I'm not aware of any update process here. The data file that is pulled from the deployed state is 
`http://github.khronos.org/glTF-Project-Explorer/data/glTF-projects-data.json`

(There are some possible hacky solutions for this, and some caveats, but before I start speculating: ) Is there any process to dedicatedly trigger an update of the deployed state?

(An aside: The project explorer could also be listed at http://github.khronos.org/ , but that's not critical right now...)

**Comment by outofcontrol** [comment]
Not sure I understand the question. The data file `http://github.khronos.org/glTF-Project-Explorer/data/glTF-projects-data.json` does exist in the deployed pages. Is there another file that is missing?

**Comment by javagl** [comment]
The file 

http://github.khronos.org/glTF-Project-Explorer/data/glTF-projects-data.json

(which seems to exist - at least, it is shown for me when I click the link) is different from the file in the repo, and there has to be some sort of update. But according to https://github.com/KhronosGroup/glTF-Project-Explorer/pull/36#issuecomment-583021281 , this is done with a "semi-manual" process, and Adam (weegeekps) mentioned that he'd do it, so there may not be an immediate action for the Khronos webmaster.

(And maybe this issue can be closed again then - sorry,  I must admit that I don't know much about certain parts of (web) infrastructures, so I might have bothered you unnecessarily...)

**Comment by weegeekps** [comment]
The issue is that we don't currently have a way of automatically performing the deployment. Everything is actually in place for doing so, except that we don't have a runner. Our original plan was to use GitHub Actions but it doesn't look like that's enabled for Khronos Repos. Maybe you can look into that @Khronoswebmaster?

In the meantime, we can do a manual deployment by executing `yarn deploy` from our forks as long as the person doing so has merge rights to master. This executes a build script to deploy the page out to the `gh-pages` branch. I'm going to document this in the DEVELOPER.md file.

**Comment by outofcontrol** [comment]
If Travis-ci would be helpful, I will enable it. You would need to figure out what the .travis.yml should contain.

**Comment by weegeekps** [comment]
I think Travis CI would work great. I will start investigating what we need in the travis config for our repo.

**Comment by outofcontrol** [comment]
If you add the Travis CI and trigger a build you should be all set. Travis-CI.com has you listed as waiting for the first build.

**Comment by javagl** [comment]
If I understood this correctly, then the build process is set up. (This issue was only about a somewhat unrelated, smaller issue - so if there are points to discuss regarding the build, it could be done in another issue).
