### ISSUE TITLE
Edit the entry for COMSOL Multiphysics

### ISSUE THREAD

**Issue by jfnhiller** [KhronosGroup/glTF-Project-Explorer#31]
Please edit the glTF-Project-Explorer entry for COMSOL Multiphysics to add the following property:description pairs:

"language" : "MATLAB"
and
"input": "DWG" , "IPT" , "IAM" , "PRT" , "ASM" , "RVT" , "PAR" , "SLDPRT" , "SLDASM" , "3MF" , "SAT" , "SAB" , "ASAT" , "ASAB" , "DXF" , "CATPART" , "CATPRODUCT" , "MPHTXT" , "MPHBIN" , "IGS" , "IGES" , "PRT" , "X_T" , "X_B" , "XMT_TXT" , "XMT_BIN" , "STEP" , "STL" , "GDS" , "VRML" , "WRL" , "CVG" , "XML" , "ZIP" , "TAR" , "TGZ" , "TAR.GZ" , "DEM"

**Comment by javagl** [comment]
The entry has been updated. Sorry for the delay.

**Comment by jfnhiller** [comment]
Hello Marco,
When I look at the page, the entry for COMSOL has not changed (see attached screenshot) as of 2/6/20. I have force-refreshed (Ctrl+R).
Do I need to do something more? Or will the updates appear later without me doing anything further?
Best,
Jeff
PS: The screenshot was produced in Google Chrome. In MS Edge, the page does not display any entry (Separate issue, I suppose)

**Comment by jfnhiller** [comment]
When I look at the page, the entry for COMSOL has not changed as of 2/6/20. I have force-refreshed (Ctrl+R).
Do I need to do something more? Or will the updates appear later without me doing anything further?

**Comment by weegeekps** [comment]
This should be showing properly now.

**Comment by jfnhiller** [comment]
Indeed it does. Thank you!
