### ISSUE TITLE
Migrate the README tables and the Late Breaking issue

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Project-Explorer#37]
The data file for the the project explorer has been initialized with the data from the tables in the README and the entries from the "Late Breaking" issue at some point. It has been updated just before the Project Explorer went public. But there have been other additions to the README table and the Late Breaking issue in the meantime.

For the final migration, there are some tasks:

- The additions to the README that have been done have to be added to the data JSON file. (This may involve some manual work, going through the commit history...)
- The additions to the Late Breaking issue have to be added (these should only be a few, IIRC)
- The "Late Breaking" issue should be closed, with a comment pointing to the README of the Project Explorer where the process of adding new entries is explained. (For short: They can be added by opening issues, or also via PRs of the edited data JSON file)
- The tables in the README should be removed and replaced with a comment and a link to the Project Explorer

The last one raises some issues:

During the call, I mentioned the anchors. For example, people may have existing links like that:

> Here are some [Python libraries for glTF](https://github.com/KhronosGroup/glTF/blob/master/README.md#python)

The link here is `https://github.com/KhronosGroup/glTF/blob/master/README.md#python`, and jumps directly to the "Python" table via the `#python` anchor. When the table is removed, the same link will point to the top of the README file. But it should (preferably) jump to the section that *originally* contained the table, but now only contains the link to the Project Explorer

---

Very roughly speaking, I thought about sneaking anchors into the README like that:

- A list of anchors that are not visible in the rendered README:

        [](https://github.com/KhronosGroup/glTF/blob/master/README.md#typescript)
        ...
        [](https://github.com/KhronosGroup/glTF/blob/master/README.md#rust)

- Followed by a common pointer to the Project Explorer:

> The tables that have been shown here have been replaced with the glTF Project Explorer, at http://github.khronos.org/glTF-Project-Explorer/ 

But I'm not sure whether this will work as expected.

--- 

@weegeekps  I think you even suggested to pass the "anchors" as filter information to the explorer. If I understood this correctly, this would **very** roughly by done with something like a "query parameter"...:

        [Python](http://github.khronos.org/glTF-Project-Explorer/?language=python)

Is that correct? 
This could be a handy functionality anyhow, but I have to clue about how complicated this is (and it's not strictly necessary for the pure replacement of the README tables...)

**Comment by javagl** [comment]
This has been addressed in the following branches:

https://github.com/javagl/glTF-Project-Explorer/tree/project-list-migration
https://github.com/javagl/glTF/tree/project-list-migration

The "change log":

---

Updated glTF-Project-Explorer data file based on the follwing commits
that had been done in the main glTF README.md:

- Updated link for Archilogic (2019-10-04, 13:22)
- Updated Esri entries (2019-10-11, 08:55)
- Added JglTF-mesh (2019-10-24, 17:38)
- (Adobe Dimension was already up to date (2019-11-06, 17:52))
- Updated gltfpack, which was formerly called "meshoptimizer" (2019-11-11, 01:44)
- (Datakit CrossManager was already contained, (2019-11-12, 10:12))
- (glTFast was already contained, (2019-12-06, 00:39))
- Updated link for Microsoft.glTF.CPP (2020-01-08, 20:54)
- (Datakit CrossCad/Ware SDK was already contained, (2020-01-31, 09:19))
- Added pygltflib (2020-02-01, 09:32)
- Added Gestaltor (2020-02-29, 15:53)

Updated glTF-Project-Explorer data file based on new entries from
the late-breaking issue:

- (Magnum Engine was already contained, https://github.com/KhronosGroup/glTF/issues/1058#issuecomment-549649735 )
- Added acl-gltf (https://github.com/KhronosGroup/glTF/issues/1058#issuecomment-563228812)
- Added Gru (https://github.com/KhronosGroup/glTF/issues/1058#issuecomment-569750758)
- Added Apple Reality Converter (https://github.com/KhronosGroup/glTF/issues/1058#issuecomment-574972471)
- Added SimpleGLTF2 (https://github.com/KhronosGroup/glTF/issues/1058#issuecomment-578369708)
- Added Amazon Sumerian (https://github.com/KhronosGroup/glTF/issues/1058#issuecomment-607887271)
- Added Arvizio (https://github.com/KhronosGroup/glTF/issues/1058#issuecomment-610483365)

Updated glTF-Project-Explorer data file based on issue about
broken links (https://github.com/KhronosGroup/glTF/issues/1786)

- Seems to be working: https://www.opencascade.com/content/cad-assistant
- Removed: https://www.assetstore.unity3d.com/#!/content/99793
- Was not contained in data file yet: https://www.assetstore.unity3d.com/#!/content/40946
- Replaced with main repo link: https://github.com/emadurandal/GLBoost/blob/master/src/js/middle_level/loader/GLTFLoader.js
- Removed: https://github.com/AnalyticalGraphicsInc/gltf-utilities
- Updated https://facebook.github.io/react-vr/ to new link
- Removed "simplygon" - it's "simply gon...e"
 (While "simplygon.com" seems to still exist, there is no information about glTF support, and the 
  links https://azuremarketplace.microsoft.com/en-us/marketplace/apps/simplygon.simplygon 
  and https://simplygonclouddoc.simplygon.com/tutorials/firstprocessing.html#asset are dead

For the main glTF README.md:
- Removed [glTF - Seattle Khronos Group Meetup](https://drive.google.com/drive/folders/0BybLPh8Iz_rebnVtbUxLVUswZVE) by Saurabh Bhatia. September 2017
- Updated link for [Why glTF 2.0 is awesome!](https://blog.ybalrid.info/2018/07/16/why-gltf-2-0-is-awesome/) by Arthur Brainville. July 2018

---

The point about "anchor links" as also addressed: The README now contains "empty links" in the "glTF Tools" section, like 

`<a id="user-content-optimizers" href="#optimizers"></a>`

This way, anchors should keep working, and a link like 

`https://github.com/javagl/glTF/tree/project-list-migration#converters-importers-and-exporters`

should directly jump to the section that links to the project explorer (instead of pointing to the top of the README). For example:

https://github.com/javagl/glTF/tree/project-list-migration#converters-importers-and-exporters

**Comment by javagl** [comment]
(If this is OK, I'd create PRs for both projects, but since it covers two projects, any discussion should preferably happen here, in *one* thread, and not in the individual PRs...)

**Comment by weegeekps** [comment]
I'm supportive of this, @javagl. Please let me know how I can help.

**Comment by javagl** [comment]
Thanks @weegeekps  

The state *could* already be PR'ed. But one of the main points is whether people are happy with the new ("lean") README, without the tables. 

(In terms of a further cleanup, one could also pull out things like the "Presentations and Articles" list from the main README into an own .MD. But maybe that's not as critical as the projects list. The latter had been a bit scattered with the README tables, the project explorer and the late-breaking issue - hopefully, this can not converge into a state that is easier to maintain...)

**Comment by javagl** [comment]
I have created two PRs

- Mainly removing the tables from the main glTF README: https://github.com/KhronosGroup/glTF/pull/1796
 - Adding/Updating the information for the project explorer: https://github.com/KhronosGroup/glTF-Project-Explorer/pull/43

Considering that there are already issues/PRs that might become obsolete, I'd like to avoid diverging too much from the master branches. The information from the following issue/PR have to be considered after merging:

- https://github.com/KhronosGroup/glTF/pull/1791
- https://github.com/KhronosGroup/glTF/issues/1795 (somewhat critical, open for 3 days already...)

**Comment by javagl** [comment]
Both PRs are merged, therefore closing.
