### ISSUE TITLE
Where to view the list of projects?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Project-Explorer#53]
When visiting http://github.khronos.org/glTF-Project-Explorer/, I see instructions for contributing but not a list of projects — have I missed the URL for that? Or is there an issue or PR to track making that list available?

**Comment by weegeekps** [comment]
Yikes, I will investigate ASAP. Not sure what happened. Stay tuned.

**Comment by weegeekps** [comment]
This is resolved. Accidentally removed `skip_cleanup` in Travis at some point.
