### ISSUE TITLE
Should the file formats differentiate between glTF and GLB?

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Project-Explorer#58]
The README currently says that for the `inputs`/`outputs` should at least include `glTF 1.0` or `glTF 2.0`, indicating the glTF version that is supported. Some entries also *explicitly* list `GLB`. 

Should differentiate between glTF and GLB somehow?

(My 2 cents: I think that there are not so many libraries that do *not* support `GLB` (and if they don't one could argue that they don't *really* support "glTF" at all...)

**Comment by donmccurdy** [comment]
I agree — support for glTF 2.0 implies support for `.glb`, and for any tool that can't load the `.glb` variant we should just report a bug. No need to list GLB separately on this explorer.

**Comment by javagl** [comment]
No further concerns, so I think this can be closed: `"glTF 2.0"` should *always* cover `GLB` as well (people might add `GLB` for searchability, but that's a different point).
