### ISSUE TITLE
New Project: Facebook Spark AR Studio

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Project-Explorer#86]
glTF import

https://sparkar.facebook.com/ar-studio/learn/articles/fundamentals/supported-file-formats/

**Comment by yearofthewhopper** [comment]
What's this note mean? @pjcozzi

**Comment by pjcozzi** [comment]
@yearofthewhopper this issue is a reminder to add Spark AR Studio to the [glTF Project Explorer list](https://github.khronos.org/glTF-Project-Explorer/).

Also see #78
