### ISSUE TITLE
New Project: Microsoft FlightSim

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Project-Explorer#93]
Perhaps it is a few different entries in Project Explorer

* 3DS Max export, https://github.com/AsoboStudio/FlightSim-glTF-exporter (and https://github.com/AsoboStudio/FlightSim-3dsMax-tools?)
* Blender exporter, https://www.fsdeveloper.com/wiki/index.php?title=Blender2MSFS
* Importers?
* FlightSim runtime itself

CC @bghgary for suggestions or corrections.

**Comment by bghgary** [comment]
I don't actually know how any of this works :-)

@lpierabella may be able to answer better.

**Comment by elpie89** [comment]
this one:  [ https://github.com/AsoboStudio/FlightSim-glTF-exporter ](https://github.com/AsoboStudio/FlightSim-glTF-exporter )  is a fork of the Babylon 3ds max exporter, it could be interesting for the community to see how ASOBO extensions have been implemented

the second one [https://github.com/AsoboStudio/FlightSim-3dsMax-tools](https://github.com/AsoboStudio/FlightSim-3dsMax-tools) is a bunch of 3ds max script to help artist developing content for MSFS.
Even if some of them are related to glTF, I do not think it worth any mention in the project explorer

The Blender exporter speaks for himself, it could be useful to see how ASOBO extensions are implemented in Blender..however, it is not maintained by Asobo.

MSFS uses tinyglTF as a glTF import library  (with some adaptations)...this is not public.

So I suggest mentioning only:
[https://github.com/AsoboStudio/FlightSim-glTF-exporter](https://github.com/AsoboStudio/FlightSim-glTF-exporter
)
[https://www.fsdeveloper.com/wiki/index.php?title=Blender2MSFS](https://www.fsdeveloper.com/wiki/index.php?title=Blender2MSFS)
and FlightSim itself.

**Comment by pjcozzi** [comment]
@elpie89 really appreciate the prompt and detailed response.  It is amazing what you have achieved with MSFS and with glTF.
